theme: jekyll-theme-minimal
title: Wellcome to my Jekyll Blog
description: Trying to push up new quick blog
categories: beginner
        city    : Royal Oak
        state   : MI
        postal  : 48046
